### ISSUE TITLE
quik не получает bt.Order.Accepted

### ISSUE THREAD

**Issue by Swest3128** [cia76/BackTraderQuik#10]
Здравствуйте, только начал работать с вашим кодом, связка  BackTrader  Quik junior python клиент.
Заявки создаются но я так понимаю от quik не получает bt.Order.Accepted.
и зависает на проверке:

 if self.order and self.order.status == bt.Order.Submitted:  # Если заявка не исполнена (отправлена брокеру)
         self.cancel(self.order)

Контакт в телеге https://t.me/SalavatN

**Comment by cia76** [comment]
Возможно, в версии junior нет функционала подписок на изменение состояния заявок. Заявка отправляется, но изменение ее статуса тогда не придет. Отсюда, неверная обработка.

Рекомендую запустить все примеры, где есть подписки. Они все должны работать.

Также в примере постановки и отмены заявок выведите через print статус заявки.
