### ISSUE TITLE
не верное отражение цены по валютным фьючерсным контрактам

### ISSUE THREAD

**Issue by wolftik** [cia76/BackTraderQuik#11]
Здравствуйте. Столкнулся с проблемой при написании стратегии, коснулась это валютный фьючерсов, при запросе цены бара по SPBFUT.CNYRUBF, SPBFUT.BRG4, SPBFUT.SiM4 и тд.
Пробовал обкатывать на вашем примере (01 - LiveTradingEvents)

Могли бы подсказать, пожалуйста, с решением, наверняка сталкивались с этим.
Я вышел из ситуации просто закомментировав в функции quik_to_bt_price деление
return price # / lot_size  # то цену делим на лот
Но возможно тут бала какая то иная задумка и этот ход не очень по джентельменски.
 
Судя по всему, дело в делении на кол-во лотов, но для фьючерсов это не актуально при построении графика

И еще вопрос=) не нашел документации квик к луа, и Ваших функциях запроса ГО покупателя и продавца по фьючерсам, есть ли такая возможность в целом?

**Comment by Celeevo** [comment]
Привет, @wolftik!
Помнится, в свое время тоже был неприятно удивлен отсутствием в "базовой комплектации" функций получения ГО. 
Как без него торговать-то фьючами?)) Для себя реализовал добавлением в QKBroker.py:

    def get_bayer_go(self, sec_name):
        return float(self.store.qpProvider.GetParamEx("SPBFUT", sec_name, "BUYDEPO")["data"]["param_value"])

    def get_seller_go(self, sec_name):
        return float(self.store.qpProvider.GetParamEx("SPBFUT", sec_name, "SELLDEPO")["data"]["param_value"])

И вызываю их из модуля со стратегией, при расчете допустимого кол-ва контрактов для сделки, например как-то так:
go = self.broker.get_bayer_go(seс)

**Comment by cia76** [comment]
Всем привет!

Конечно, разработчик BackTrader понятия не имел, что с его библиотекой будут торговать российский рынок. Поэтому, он не учел многих сущностей. Вы верно отметили отсутствие ГО. Я к этому еще добавлю расписание работы биржи. Разные тикеры торгуются по разным расписаниям. Да и пауз/клирингов внутри сессии бывает несколько.

Есть 2 подхода решения этих задач:

1. Создавать свои сущности внутри BackTrader как делает @Celeevo
2. Уходить от BackTrader и создавать свою библиотеку автоторговли

**Comment by wolftik** [comment]
Большое спасибо @Celeevo, сделал по аналогии. Пытаюсь в целом обойтись без BackTrader, по факту мы имеем прекрасную вашу @cia76 библиотеку QuikPY. По факту все инструменты из квика уже доступны в благодаря lua и бесконечному циклу. Зачем, пока не придумал, но можно=) лень просто разбираться в BackTrader
