### ISSUE TITLE
Did you mean: 'GetCandlesFromDataSource'?

### ISSUE THREAD

**Issue by AlexTheEngineer-cccp** [cia76/BackTraderQuik#13]
Добрый день!

Вот такое выскакивает:

 File "C:\Users\mw1b5565\PycharmProjects\testBT01\BackTraderQuik\QKData.py", line 51, in start
    json_bars = self.store.provider.get_candles_from_data_source(self.classCode, self.secCode, self.interval, 0)['data']  # Получаем все бары из QUIK
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuikPy' object has no attribute 'get_candles_from_data_source'. Did you mean: 'GetCandlesFromDataSource'?

В более старой версии файла на этом месте действительно вызывается GetCandlesFromDataSource.

Если что не так, то заранее извиняюсь. Я впервые пишу issue в Git )

**Comment by cia76** [comment]
Сейчас готовлю новую версию QuikPy. В ней приведу все вызовы функций к единому виду. Как опубликую, ошибки этой не будет.
