### ISSUE TITLE
Ошибка  dt_json = bar['datetime'] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ipARTEM** [cia76/BackTraderQuik#14]
Добрый день, Игорь! Подскажите, пожалуйста, при запуске примеров OCO.py и Brackets.py возникает ошибка 

...\BackTraderQuik\QKData.py", line 145, in get_bar_open_date_time dt_json = bar['datetime']  # Получаем составное значение даты и времени открытия бара
TypeError: string indices must be integers

Что можно сделать, чтобы устранить ошибку? Спасибо))

**Comment by ipARTEM** [comment]
Все отлично работает, я разобрался))

**Comment by Ra-M497** [comment]
Подскажите, пожалуйста, как решить данную проблему? Начал работу в PyCharm. Появилась такая же ошибка в файле QKStore.py.

**Comment by cia76** [comment]
Рекомендую подождать новую версию API от Финама. Текущая версия не развивается и не поддерживается Финамом.
