### ISSUE TITLE
symbol.py 

### ISSUE THREAD

**Issue by Monstrello** [cia76/BackTraderQuik#15]
Добрый день!
Получаю ошибку при выполнении **symbol.py** и **symbols.py**

_line 44, in getdata
    return cls.DataCls(*args, **kwargs)
TypeError: 'NoneType' object is not callable_

Буду признателен за помощь, где копать?

Остальные скрипты примеров исполняются корректно (к Quik подключение работает)

**Comment by cia76** [comment]
В новой сборке примеры рабочие
