### ISSUE TITLE
Интеграция с QuikPy

### ISSUE THREAD

**Issue by Celeevo** [cia76/BackTraderQuik#16]
Земной поклон, мастер @cia76!
Решил тут обновить ваши библиотечки BTQuik и QuikPy с самых первых эксклюзивных версий, и обнаружил, что новые походу где-то рассинхронились, будучи установленными с гит-хаба в их крайних версиях. Я для себя их конечно засинхронил, но видимо нужен фикс для общественности, пул-реквесты не осилю, поэтому по тексту:

1. AttributeError: 'QuikPy' object has no attribute 'is_subscribed':
В BackTraderQuik/QKData.py, поменять в строке 68:
self.store.provider.is_subscribed -> self.store.provider.IsSubscribed

2. AttributeError: 'QuikPy' object has no attribute 'subscribe_to_candles':
В BackTraderQuik/QKData.py, поменять в строке 69:
self.store.provider.subscribe_to_candles -> self.store.provider.SubscribeToCandles

3. AttributeError: 'QuikPy' object has no attribute 'get_info_param':
В BackTraderQuik/QKData.py, поменять в строках 159-160:
get_info_param -> GetInfoParam

4. Строки 51 и 112 QKData.py по аналогии

Ну или как-то подругому, чтобы BTQuik и QuikPy дружили. 
Да пребудет с нами профит!

**Comment by cia76** [comment]
В новой сборке код рабочий
