### ISSUE TITLE
Последняя свеча торговой сессии

### ISSUE THREAD

**Issue by Celeevo** [cia76/BackTraderQuik#2]
Добрый вечер, 
я использую торговую стратегию в ВТ для фьючерсов на часовом ТФ, и мне дорога каждая свеча). А по существующей в QKData логике, последняя свеча сессии помечается DELAYED (c liveMode = False), т.к. приходит из Quik на следующий день. И как следствие, эта свеча не попадает в обработку метода NEXT стратегии, на ней нельзя отлавливать сигналы на вход/выход в/из позиции, хотя это обычная торговая свеча, на закрытии которой (условно в 7:00) мы можем это делать (отлавливать сигналы). Думаю, логика будет работать также и на младших ТФ. Можно как-то элегантно поправить эту ситуацию?

Это происходит здесь:
        # Бывает ситуация, когда QUIK несколько минут не передает новые бары. Затем передает все пропущенные
        # Чтобы не совершать сделки на истории, меняем режим торгов на историю до прихода нового бара
        elif self.liveMode and dtMarketNextBarClose <= dtMarketNow:  # Если в режиме получения новых баров, и следующий бар закроется до текущего времени на бирже
            self.put_notification(self.DELAYED)  # Отправляем уведомление об отправке исторических (не новых) баров
            self.liveMode = False  # Переходим в режим получения истории

**Comment by cia76** [comment]
Я тестировал на 1 и 5-и минутках. Вот как это работает, на примере минутного графика. После того, как вся история баров подгружена, BT ждет новый бар. Как только он приходит, то идет переход в режим LIVE, где вы можете торговать. Последний бар торговой сессии формируется после того, как сессия закончилась.

Мы работаем с событием next. Это значит приход следующего бара. Когда будет следующий бар? Это будет первая пришедшая минутка на открытии следующей сессии. Поэтому, да, в некотором виде бар пропускаем. Для минуток это будет последняя минута сессии.

Чтобы получать последнюю минутку на открытии сессии, нужно или вводить понятие времени открытия биржи, или подписаться на сделки и ждать первой сделки в сессии. Тогда и выдавать последнюю минутку.

**Comment by cia76** [comment]
Я подумаю как это можно вписать в существующий алгоритм.

**Comment by cia76** [comment]
В последней сборке решил эту задачу. Последняя свеча сессии приходит на открытии следующей сессии.
