### ISSUE TITLE
Добавить параметр ClientCodeTerminal, для случаев когда Код Клиента не соответствует Номеру Терминала.

### ISSUE THREAD

**Issue by WISEPLAT** [cia76/BackTraderQuik#3]
Добрый день! Классная библиотека у вас! Спасибо!
Хочу предложить добавить ClientCodeTerminal в class QKBroker, для того, чтобы можно было делать заявки в Quik, в случаях, когда Код Клиента не соответствует Номеру Терминала. - например такое у меня случилось в брокере Финам, а в брокере Открытие - все ок.
Сделал это в форке https://github.com/WISEPLAT/BackTraderQuik/commit/76e3d195ae42251ac0a435690b8ec37fb85f20fc
Плиз, посмотрите и дайте обратную связь. Спасибо!

**Comment by WISEPLAT** [comment]
Доступен по телеграму https://t.me/OlegSh777

**Comment by cia76** [comment]
Добрый день!

Идея понятна. Есть Код Клиента. Есть Код Терминала. Если Код Терминала отличается от Кода Клиента, то в заявку на покупку/продажу нужно подавать Код Терминала.

Непонятна сама сущность Кода Терминала. Можете скинуть ссылки, где про это рассказывается?

Получается, что изменения нужно также вносить не только в CreateOrder, но и в GetPositions, GetMoneyLimits

**Comment by WISEPLAT** [comment]
Добрый! 

Ссылка есть только [такая](https://zen.yandex.ru/media/id/5e9a612424270736479fad54/bitva-s-finam-624f12acc3c38f063178ca95) - т.к. эта ситуация наблюдается у финам (выяснил методом эксперимента, а потом звонил в их поддержку и получил подтверждение), а у нормального брокера Открытие - все Ок - Код Клиента == Номеру Терминала.

Открытым текстом так и сказали - что у них Номер Терминала - только для выставления заявок, а Код Клиента - для доступа к финансам.

По поводу GetPositions, GetMoneyLimits - нужно проверить, т.к. это финансы. Сегодня - завтра протестирую)))

**Comment by WISEPLAT** [comment]
Добрый день) Протестировал, достаточно только этих изменений. Т.к. и заявки выставлять могу + их вижу, позиции вижу и деньги вижу. Проверял в прямом [эфире](https://www.youtube.com/watch?v=ukWcRQICOZw) во время торгов.

**Comment by WISEPLAT** [comment]
Спасибо! Вчера [протестировал в прямом эфире ](https://www.youtube.com/watch?v=Negg_dBwaEA)- всё ОК!
Добавил [комментарий в статью](https://zen.yandex.ru/media/id/5e9a612424270736479fad54/bitva-s-finam-624f12acc3c38f063178ca95) о позитивном решении в статью про "необычного" брокера))
