### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by Celeevo** [cia76/BackTraderQuik#6]
Добрый день, 
подскажите пжлст, поддерживаемая вами версия BackTrader готова к работе на 3.11? 
Если нет, есть в планах адаптация?
Если да, заметили после перехода на 3.11 увеличение быстродействия?

**Comment by cia76** [comment]
Добрый день!

У меня в репозитории лежит "вилка" оригинального BT с некоторыми исправлениями. Библиотека корректно работает в версии Python 3.10

Думаю, что с версией 3.11 также проблем не будет.

Что касается производительности. Python сам по себе не производителен. Его большой плюс - это кроссплатформенность и распространенность. Хоть на суперкомпьютере можно запускать, хоть на микроконтроллере. Не думаю, что быстродействие сильно увеличится.
