### ISSUE TITLE
Проблема с мульти-таймфреймами при использовании данных с Quik

### ISSUE THREAD

**Issue by WISEPLAT** [cia76/BackTraderQuik#7]
Добрый вечер! Тестировал работу тикера с мульти-таймфреймом, т.е. сразу пытался добавить H1 и D1, для стратегии основанной на нескольких таймфреймах, и выявил некоторую проблему, она показана в видео: [https://youtu.be/JVE1--yDGWQ](https://youtu.be/JVE1--yDGWQ) 
Если использую данные из CSV для H1 и D1 - то мультитаймфрейм работает нормально - тикер пробегается по обеим таймфреймам - синхронизируясь по дате (данные не из quik - все ок).
Если использовать live данные получаемые из quik через store.getdata - то по одному таймфрейму происходит вызов NEXT, а по другому - нет следующего бара - всегда выдается один и тот же.
Прошу по возможность посмотреть это видео с описанием проблемы и подсказать что можно поднастроить для правильной работы с мульти-таймфреймами, когда данные получаем через quik.
Код доступен по этой ссылке: [https://github.com/WISEPLAT/Learn-BackTrader/commit/3c68b490156a3d96a026eaffa4bf9b4e0d12ba5b](https://github.com/WISEPLAT/Learn-BackTrader/commit/3c68b490156a3d96a026eaffa4bf9b4e0d12ba5b)
+ Там же выложены файлы CSV для теста работы мульти-таймфрейма.
+ Для удобства прикладываю их здесь.
[TQBR.SBER_D1.csv](https://github.com/cia76/BackTraderQuik/files/10310441/TQBR.SBER_D1.csv)
[TQBR.SBER_H1.csv](https://github.com/cia76/BackTraderQuik/files/10310442/TQBR.SBER_H1.csv)

Плиз, посмотрите и дайте обратную связь. Спасибо!
P.S. Доступен по телеграму https://t.me/OlegSh777

Вот сам код: 

from datetime import datetime
from backtrader import Cerebro, TimeFrame, Strategy, feeds
from BackTraderQuik.QKStore import QKStore  # Хранилище QUIK
import backtrader as bt
import pandas as pd

class PrintStatusAndBars(Strategy):
    """
    - Отображает статус подключения
    - При приходе нового бара отображает его цены/объем
    - Отображает статус перехода к новым барам
    """
    params = (  # Параметры торговой системы
        ('name', ''),  # Название торговой системы
        ('symbols', ''),  # Список торгуемых тикеров. По умолчанию торгуем все тикеры
    )

    def log(self, data, txt, dt=None):
        """Вывод строки с датой на консоль"""
        dt = bt.num2date(data.datetime[0]) if dt is None else dt  # Заданная дата или дата последнего бара первого тикера ТС
        print(f'{dt.strftime("%d.%m.%Y %H:%M")}, {txt}')  # Выводим дату и время с заданным текстом на консоль

    def __init__(self):
        """Инициализация торговой системы"""
        self.isLive = False  # Сначала будут приходить исторические данные

    def next(self):
        """
        Приход нового бара тикера
        """
        # if self.p.name != '':  # Если указали название торговой системы, то будем ждать прихода всех баров
        #     lastdatetimes = [bt.num2date(data.datetime[0]) for data in self.datas]  # Дата и время последнего бара каждого тикера
        #     if lastdatetimes.count(lastdatetimes[0]) != len(lastdatetimes):  # Если дата и время последних баров не идентичны
        #         return  # то еще не пришли все новые бары. Ждем дальше, выходим
        #     print(self.p.name)
        for data in self.datas:  # Пробегаемся по всем запрошенным тикерам
            if self.p.symbols == '' or data._dataname in self.p.symbols:  # Если торгуем все тикеры или данный тикер
                self.log(data, f'{data._name} - {bt.TimeFrame.Names[data.p.timeframe]} {data.p.compression} - Open={data.open[0]:.2f}, High={data.high[0]:.2f}, Low={data.low[0]:.2f}, Close={data.close[0]:.2f}, Volume={data.volume[0]:.0f}',
                     bt.num2date(data.datetime[0]))
                # if data._name == "_m60":
                #     print("M60")
                #     print("D1", bt.num2date(self.datas[1].datetime[0]))

    def notify_data(self, data, status, *args, **kwargs):
        """Изменение статсуса приходящих баров"""
        dataStatus = data._getstatusname(status)  # Получаем статус (только при LiveBars=True)
        print(f'{data._dataname} - {dataStatus}')  # Статус приходит для каждого тикера отдельно
        self.isLive = dataStatus == 'LIVE'  # В Live режим переходим после перехода первого тикера

if __name__ == '__main__':  # Точка входа при запуске этого скрипта
    cerebro = Cerebro()  # Инициируем "движок" BackTrader

    # Несколько временнЫх интервалов, прямая загрузка
    symbol = 'TQBR.GAZP'
    store = QKStore()  # Хранилище QUIK (QUIK на локальном компьютере)
    # store = QKStore(Host='<Ваш IP адрес>')  # Хранилище QUIK (К QUIK на удаленном компьютере обращаемся по IP или названию)

    data = store.getdata(dataname=symbol, timeframe=TimeFrame.Minutes, compression=60, fromdate=datetime(2022, 12, 15),
                         name="_m60",
                         LiveBars=True)  # Исторические данные по малому временнОму интервалу (должен идти первым)
    # data = pd.read_csv("TQBR.SBER_H1.csv", sep=",", index_col='datetime')  # Считываем файл в DataFrame
    # data.index = pd.to_datetime(data.index, format='%Y-%m-%d %H:%M')  # Переводим индекс в формат datetime
    # data = feeds.PandasData(dataname=data, name="_m60")
    cerebro.adddata(data)  # Добавляем данные

    # cerebro.resampledata(data, timeframe=TimeFrame.Days, compression=1).plotinfo.plot = False

    data = store.getdata(dataname=symbol, timeframe=TimeFrame.Days, compression=1, fromdate=datetime(2022, 12, 15),
                         name="_d1",
                         LiveBars=True)  # Исторические данные по большому временнОму интервалу
    # data = pd.read_csv("TQBR.SBER_D1.csv", sep=",", index_col='datetime')  # Считываем файл в DataFrame
    # data.index = pd.to_datetime(data.index, format='%Y-%m-%d %H:%M')  # Переводим индекс в формат datetime
    # data = feeds.PandasData(dataname=data, name="_d1")
    cerebro.adddata(data)  # Добавляем данные

    cerebro.addstrategy(PrintStatusAndBars)  # Добавляем торговую систему

    cerebro.run()  # Запуск торговой системы
    # cerebro.plot()  # Рисуем график. Требуется matplotlib версии 3.2.2 (pip install matplotlib==3.2.2)

**Comment by Celeevo** [comment]
Добрый день, 
у меня ваш код при получении данных из QUIK воспроизводится без указанной ошибки. Есть о чем задуматься.)
...
15.12.2022 22:00, _m60 - Minutes 60 - Open=160.67, High=160.69, Low=160.30, Close=160.42, Volume=32654
15.12.2022 00:00, _d1 - Days 1 - Open=160.74, High=161.25, Low=157.72, Close=160.31, Volume=2202315
15.12.2022 23:00, _m60 - Minutes 60 - Open=160.41, High=160.62, Low=160.30, Close=160.31, Volume=26442
15.12.2022 00:00, _d1 - Days 1 - **Open=160.74, High=161.25, Low=157.72, Close=160.31, Volume=2202315**
15.12.2022 23:00, _m60 - Minutes 60 - Open=160.41, High=160.62, Low=160.30, Close=160.31, Volume=26442
16.12.2022 00:00, _d1 - Days 1 - **Open=160.21, High=162.48, Low=159.95, Close=160.24, Volume=1372683**
16.12.2022 09:00, _m60 - Minutes 60 - Open=160.21, High=160.21, Low=160.21, Close=160.21, Volume=1581
16.12.2022 00:00, _d1 - Days 1 - Open=160.21, High=162.48, Low=159.95, Close=160.24, Volume=1372683
16.12.2022 10:00, _m60 - Minutes 60 - Open=160.30, High=161.24, Low=159.95, Close=161.15, Volume=187501
16.12.2022 00:00, _d1 - Days 1 - Open=160.21, High=162.48, Low=159.95, Close=160.24, Volume=1372683
...

**Comment by WISEPLAT** [comment]
Хм, странно.
Для чистоты эксперимента создал проект с нуля - только для этого файла https://github.com/WISEPLAT/Learn-BackTrader/commit/3c68b490156a3d96a026eaffa4bf9b4e0d12ba5b - и ошибка сохраняется:
05.01.2023 14:00, _m60 - Minutes 60 - Open=161.23, High=161.40, Low=161.20, Close=161.38, Volume=29736
10.01.2023 00:00, _d1 - Days 1 - Open=162.71, High=162.98, Low=161.44, Close=162.10, Volume=734843
05.01.2023 15:00, _m60 - Minutes 60 - Open=161.38, High=161.58, Low=161.31, Close=161.54, Volume=25198
10.01.2023 00:00, _d1 - Days 1 - Open=162.71, High=162.98, Low=161.44, Close=162.10, Volume=734843
05.01.2023 16:00, _m60 - Minutes 60 - Open=161.56, High=161.56, Low=161.21, Close=161.32, Volume=21462
10.01.2023 00:00, _d1 - Days 1 - Open=162.71, High=162.98, Low=161.44, Close=162.10, Volume=734843
05.01.2023 17:00, _m60 - Minutes 60 - Open=161.32, High=161.55, Low=161.00, Close=161.48, Volume=78170
10.01.2023 00:00, _d1 - Days 1 - Open=162.71, High=162.98, Low=161.44, Close=162.10, Volume=734843
05.01.2023 18:00, _m60 - Minutes 60 - Open=161.49, High=161.85, Low=161.25, Close=161.25, Volume=64796
10.01.2023 00:00, _d1 - Days 1 - Open=162.71, High=162.98, Low=161.44, Close=162.10, Volume=734843

**Comment by WISEPLAT** [comment]
> Добрый день, у меня ваш код при получении данных из QUIK воспроизводится без указанной ошибки. Есть о чем задуматься.) ... 15.12.2022 22:00, _m60 - Minutes 60 - Open=160.67, High=160.69, Low=160.30, Close=160.42, Volume=32654 15.12.2022 00:00, _d1 - Days 1 - Open=160.74, High=161.25, Low=157.72, Close=160.31, Volume=2202315 15.12.2022 23:00, _m60 - Minutes 60 - Open=160.41, High=160.62, Low=160.30, Close=160.31, Volume=26442 15.12.2022 00:00, _d1 - Days 1 - **Open=160.74, High=161.25, Low=157.72, Close=160.31, Volume=2202315** 15.12.2022 23:00, _m60 - Minutes 60 - Open=160.41, High=160.62, Low=160.30, Close=160.31, Volume=26442 16.12.2022 00:00, _d1 - Days 1 - **Open=160.21, High=162.48, Low=159.95, Close=160.24, Volume=1372683** 16.12.2022 09:00, _m60 - Minutes 60 - Open=160.21, High=160.21, Low=160.21, Close=160.21, Volume=1581 16.12.2022 00:00, _d1 - Days 1 - Open=160.21, High=162.48, Low=159.95, Close=160.24, Volume=1372683 16.12.2022 10:00, _m60 - Minutes 60 - Open=160.30, High=161.24, Low=159.95, Close=161.15, Volume=187501 16.12.2022 00:00, _d1 - Days 1 - Open=160.21, High=162.48, Low=159.95, Close=160.24, Volume=1372683 ...

Можете видос записать - как у вас отрабатывает - посмотрим))

**Comment by Celeevo** [comment]
> Можете видос записать - как у вас отрабатывает - посмотрим))

Без проблем, давайте посмотрим под композицию "Don't Stop Believin'", что означает "Не переставай верить")).
https://disk.yandex.ru/i/zspKlMu-9cIZHg

**Comment by WISEPLAT** [comment]
> > Можете видос записать - как у вас отрабатывает - посмотрим))
> 
> Без проблем, давайте посмотрим под композицию "Don't Stop Believin'", что означает "Не переставай верить")). https://disk.yandex.ru/i/zspKlMu-9cIZHg

Круто! Спасибо - вижу что у вас отрабатывает как нужно, если бы было внесено это изменение.
Тогда какого брокера вы используете?
QuikSharp.lua какой версии?
Робота под заказ пишите? Или для себя? Вижу делаете интеграцию с телеграмом - пушит сигналы в канал?

P.S., у меня на Финаме проблема наблюдается... после предложенного мною исправления кода - все ок.

**Comment by Celeevo** [comment]
> Круто! Спасибо - вижу что у вас отрабатывает как нужно, если бы было внесено это изменение. Тогда какого брокера вы используете? 

_Я знал, что понравится, спасибо). Сижу квалом на БКС и не дергаюсь._

QuikSharp.lua какой версии?
_Не знаю, та, что была в первой версии QuikPy._

Робота под заказ пишите? Или для себя? 
_Да не, я не настоящий алго-сварщик, хобби)._ 

Вижу делаете интеграцию с телеграмом - пушит сигналы в канал?
_Сигналы: заявка, вход, выход - это БКС-приложуха пушит. Телега - для notify о падении интернета, у меня примерно раз в месяц бывает, деревня жеж. В таких случаях робота приходится перезапускать (после появления инета ессествено), ибо портятся индюки после восстановления. И для P&L по завершенным сделкам - очень важно оперативно понимать, чем вечером платить за пиво: честно нажитыми или мытьем посуды в баре!))._

**Comment by WISEPLAT** [comment]
Спасибо, за решенный кейс. 
https://github.com/cia76/BackTraderQuik/commit/3e909ed9b8c9e7c9dba49cac62b462c4362b5e68
https://github.com/cia76/BackTraderQuik/commit/94e1b50d6cb002fcbf9aaef278fd2c4051b5a2ea
