### ISSUE TITLE
ошибка создания QuikPy

### ISSUE THREAD

**Issue by SatCat** [cia76/BackTraderQuik#9]
здесь
https://github.com/cia76/BackTraderQuik/blob/126a3e4ef038beb7a6cb696a95e8712ea970fddc/QKStore.py#L54
нужно наверное строчными --  host, requests_port, callbacks_port

**Comment by cia76** [comment]
Параметры исправил.

**Comment by cia76** [comment]
store = QKStore(Host='192.168.1.10')  # Хранилище QUIK
